### ISSUE TITLE
Cannot exit from the program Image Capture

### ISSUE THREAD

**Issue by Rahul-Venugopal** [PeterQuinn925/Squirrel#1]
Hi ,
I wrote the code for capturing images from [here ](https://hackaday.io/project/156926-squirrel-deterrent/details) .

I copied the code for capturing images and wrote it in jupyter notebook . Everything is working fine but I am not able to exit from the loop and stop the program .

As I understood 

`key = cv2.waitKey(10)`
 ` if key == 27:`
` #cv2.destroyWindow(winName) #commented out for headless`
    `break`
`print ("Goodbye")`

should stop the program when I press `esc` key . But the output is always `-1` and can anyone help me to know why the program is not stopping when I press `esc` key.

Thanks in advance

**Comment by PeterQuinn925** [comment]
If you're running it as written (as headless) there's no UI to capture the keystroke. You'll have to kill the process.  It's intended to run silently and unattended. 

If you want a UI, uncomment the lines marked 

> #commented out for headless

and then there is a cv2 window that can accept the <esc> key.

**Comment by Rahul-Venugopal** [comment]
Hi @PeterQuinn925 

Yeah , i did not notice that. Thanks for helping and I really appreciate your work. Waiting for next phases to come out . :+1:
